### ISSUE TITLE
Implement the LabelLookup Controller Get method

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/clinical-trials-listing-api#10]
## As an application developer, I want to retrieve a `LabelInformation` document by either its pretty-url name or its identifer string, so that I can lookup label..

> **ESTIMATE** TBD

### Acceptance Criteria

```gherkin
Scenario: Get label by specifying either its pretty-url or its identifier.
  Given path '/label-lookup', searchString
  When  method get
  Then  status 200
    And match response == read ('expected result file')

Examples:
   | searchString    | expected               |
   | basic-science   | pretty-url-result.json |
   | supportive_care | identfier-result       |


Scenario: Get label with invalid string.
  Given path '/label-lookup', 'chicken'
  When  method get
  Then  status 404

```

### Notes

---

### Prerequisites
- Set up API scaffolding - Issue #1 

### Tasks
- 

### Technical Notes
-

**Comment by sarinapadilla** [comment]
Closed by https://github.com/NCIOCPL/cts-dynamic-listing-api/commit/0dbd4ab58b8cfba25f6caeeb009a4078305166ee
