### ISSUE TITLE
On the /get endpoint, a group of c-code parameters where any does not return a ListingInformation should return a 404

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/clinical-trials-listing-api#34]
### Issue description
Currently, if you query the get endpoint with params ccode=chicken and ccode=C1234, then you get back the listing for C1234.
The API should return a 404 if any of the codes in the given query param list does not find a match.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  https://webapis-dev.cancer.gov/triallistingsupport/v1/listing-information/get?ccode=chicken&ccode=C1234
2. See that the ListingInformation for C1234 is returned instead of a 404

### What's the expected result?
- The API returns a 404

### What's the actual result?
- The API returns the ListingInformation for C1234

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by blairlearn** [comment]
As of Elasticsearch v5.6.x, the _terms_ query returns any records where the list of values _intersects with_ the requested values (versus only finding records where they are a subset or full match).  It is therefore necessary to add logic to the service to emulate the desired behavior.
