### ISSUE TITLE
Enabler: Clinical Trial Listing Support API Update to .Net 3.1

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/clinical-trials-listing-api#53]
The Clinical Trials Listing API presently uses .Net Core 2.1. [That version is end-of-life on August 21.](https://dotnet.microsoft.com/download/dotnet)

The new long term support version is 3.1 (released May 11).  End-of-life for that version in December of 2022.

The updated API should use [a self-contained runtime](https://docs.microsoft.com/en-us/dotnet/core/deploying/#publish-self-contained).

**Comment by VictoriaSunNIH** [comment]
This should not be a breaking change.  Smoketesting of the application would be enough. Integration tests should take care of the rest.

Not a release for the app, just for the API.
