### ISSUE TITLE
Missing trial lists

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/clinical-trials-listing-api#55]
### Issue description
A number of links to lists of trials have stopped working since dynamic listing pages went live.  This turns out to be due to an updated list of overrides not being provided to the data ingestion process.

For whatever historical reason, there have only ever been overrides for disease names, not interventions.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Browse to https://www.cancer.gov/about-cancer/treatment/clinical-trials/disease/stomach-cancer

### What's the expected result?
- A list of clinical trials for "Gastric (Stomach) Cancer"

### What's the actual result?
- A "Page Not Found" message.

**Comment by blairlearn** [comment]
The missing overrides are
```
C3918|<INHERIT>|extragonadal-germ-cell-tumors
C4699|<INHERIT>|gestational-trophoblastic-disease
C9231|<INHERIT>|merkel-cell
C27262|<INHERIT>|myelodysplastic-myeloproliferative
C4345|<INHERIT>|myloproliferative-neoplasm
C2926|<INHERIT>|non-small-cell-lung
C27031|Pancreatic Islet Cell Tumors|pancreatic-islet-cell
C4906|<INHERIT>|parathyroid-cancer
C4914|<INHERIT>|skin-cancer
C4911|<INHERIT>|stomach-cancer
C7510|Thyroid Cancer|thyroid-cancer
C3812|<INHERIT>|unknown-primary
C2955|Colorectal Cancer|colorectal-cancer
C3163|<INHERIT>|cll
C7320,C3174|<INHERIT>|cml
```

**Comment by blairlearn** [comment]
The list of overrides has been processed on the DEV API server.

Next steps are:
1. Verify the list of overrides works. (Likely @alinai)
2. Promote the updated override list to prod. (@bkline)
3. Importer runs
4. The overrides are available.

**Comment by alinai** [comment]
@blairlearn , @amydugan , Verified that the list of overrides listed on https://github.com/NCIOCPL/clinical-trials-listing-api/issues/55 works as expected for .../clinical-trials/disease.

**Comment by bkline** [comment]
The latest override list has been used for this weekend's production load.

**Comment by blairlearn** [comment]
Thank you all for seeing this to completion.
